export const SET_SELECTED_JOB = "SET_SELECTED_JOB";
export const CLEAR_SELECTED_JOB = "CLEAR_SELECTED_JOB";
export const SET_JOB_APPLICATIONS = "SET_JOB_APPLICATIONS";
export const CLEAR_JOB_APPLICATIONS = "CLEAR_JOB_APPLICATIONS";
