export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const SET_CATEGORIES_TYPE_DATA = 'SET_CATEGORIES_TYPE_DATA';
export const CATEGORIES_JOB_POSITION = 'CATEGORIES_JOB_POSITION';

